<a href="https://colab.research.google.com/github/SanjishMaharjan/LearnTorch/blob/main/PytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 1

In [ ]:
!nvidia-smi

In [ ]:
print("We are gonna learn pytorch")

We are gonna learn pytorch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# Random Tensors

# Create a random tensor of size(3,4)

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.8178, 0.8105, 0.0414, 0.6775],
        [0.3812, 0.3515, 0.0088, 0.2567],
        [0.0507, 0.4009, 0.2694, 0.2980]])

In [ ]:
random_tensor.ndim

2

# Create a random tensor with similar shape to a image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # height ,width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensors-like
#use torch.range()

In [ ]:
one_to_ten = torch.arange(1,11)
torch.arange(start=1,end=11,step=2) # can also be written with steps

tensor([1, 3, 5, 7, 9])

In [ ]:
# Creating tensors like to create a sequence of zeros
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
### Note: Tensor Datatypes are 3 big issues that we run into with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
dtype= None,
device = None,
requires_grad = False) # Whether or not to track your gradients
float_32_tensor, float_32_tensor.dtype


(tensor([3., 6., 9.]), torch.float32)

#### Converting float 32 tensor into float 16 tensor

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor # No error will occur

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = float_32_tensor.type(torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

# Getting information form tensors

In [ ]:
# create a some random tensor
some_tensor = torch.rand(3,5)
some_tensor

tensor([[0.0717, 0.7755, 0.6545, 0.7568, 0.1536],
        [0.8165, 0.6807, 0.7271, 0.3732, 0.1530],
        [0.0387, 0.8309, 0.7024, 0.9074, 0.4870]])

In [ ]:
print(f"Data type of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor is on : {some_tensor.device}")

Data type of tensor : torch.float32
Shape of tensor : torch.Size([3, 5])
Device of tensor is on : cpu
